apiVersion: apps/v1
kind: Deployment
metadata:
  name: phonebook-app-deploy
  labels:
    app: phonebook-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: phonebook-app-pod
  template:
    metadata:
      name: phonebook-app-pod
      labels:
        name: phonebook-app-pod
    spec:
      containers:
        - name: phonebook-app
          resources:
          image: devenes/python_web_server:2
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-admin-password
          envFrom:
            - configMapRef:
                name: servers-configmap
