apiVersion: v1
kind: Service
metadata:
  labels:
    app: webserver-deploy
  name: webserver-svc
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30001
  selector:
    app: webserver-deploy
  type: NodePort
