name: Docker Deployment for Result Server

on:
  workflow_dispatch:

  push:
    branches:
      - "release"
      - "test"

  pull_request:
    branches:
      - "release"
      - "test"

jobs:
  dockerx:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Find subdirectories
        run: |
          pwd
          ls -R
          cd 
          pwd         
          ls -R | grep "kubernetes-microservice-app"
          ls -R | grep "result_server"

      # - name: Build and push
      #   run: |
      #     git clone -b release --single-branch https://github.com/devenes/kubernetes-microservice-app.git
      #     cd kubernetes-microservice-app/result_server
      #     docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/python_result_server:${{github.run_number}}.0 .
      #     docker push ${{ secrets.DOCKERHUB_USERNAME }}/python_result_server:${{github.run_number}}.0
