name: Docker Deployment for Web Server

on:
  workflow_dispatch:

  push:
    branches:
      - "release"

  pull_request:
    branches:
      - "release"

defaults:
  run:
    working-directory: /web_server

jobs:
  dockerx:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # - name: Build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     file: ./web_server/Dockerfile
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/python_web_server:${{github.run_number}}.0

      - name: Build and push
        uses: docker/build-push-action@v2
        run: |
          cd web_server
          docker build --platform linux/amd64,linux/arm64,linux/arm/v7 -t ${{ secrets.DOCKERHUB_USERNAME }}/python_web_server:${{github.run_number}}.0 .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/python_web_server:${{github.run_number}}.0
